name: Update AWS permissions docs
on:
  schedule:
    - cron: "0 9 * * *"
  workflow_dispatch:

jobs:
  update-docs:
    name: Update AWS permissions docs
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout docs
        uses: actions/checkout@v4
      - name: Grab docs
        run: |
          mkdir -p docs/snippets
          curl https://porter-role.s3.us-east-2.amazonaws.com/permissions-docs.txt > docs/snippets/aws-permissions.mdx
      - name: Commit docs
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "docs: update AWS permissions docs"
          file_pattern: "docs/snippets/aws-permissions.mdx"
          commit_user_email: support@porter.run
          commit_user_name: portersupport
          commit_author: portersupport <support@porter.run>
